import type { Metadata } from "next";
import "./styles/globals.css";
import Footer from './widgets/Footer/Footer';



export const metadata: Metadata = {
  title: "MyApp",
  description: "Generated by Andrei",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
